paths: 
  /api/auth/products/:
    get:
      summary: Todos los Products
      tags:
        - Product
      responses:
        "200":
          description:
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    description: Titulo del producto
                  description:
                    type: String
                    description: Descripcion del producto
                  code:
                    type: String
                    description: Codigo del producto
                  price:
                    type: Number
                    description: Precio del producto
                  status:
                    type: Boolean
                    description: Status
                  stock:
                    type: Number
                    description:  Cantidad de stock
                  category:
                    type: String
                    description: Categoria del producto
                  thumbnails:
                    type: String
                    description: Imagen
        "500":
          description: Error interno del Server
    post:
      summary: Cargar un Product
      tags:
        - Product
  /api/auth/products/{pid}:
    get:
      summary: Un producto en particular
      tags:
        - Product
    put:
      summary: Modificar un producto en particular
      tags:
        - Product
    delete:
      summary: Borrar un producto en particular
      tags:
        - Product
  /api/auth/products/mocking/products:
    get:
      summary: Products mocking
      tags:
        - Product